# Generated by Django 4.1.5 on 2023-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_images/foto_perfil_default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
