# Generated by Django 4.1.5 on 2023-01-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('face', 'face'), ('body', 'body')], max_length=15)),
                ('imagen', models.ImageField(null=True, upload_to='home_images')),
            ],
        ),
    ]
