# Generated by Django 4.1.5 on 2023-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('Maquillajes', 'Maquillajes'), ('Accesorios', 'Accesorios')], max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
