# Generated by Django 4.1.5 on 2023-01-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imagen',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
