# Generated by Django 4.1.5 on 2023-01-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagen',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
