# Generated by Django 4.1.5 on 2023-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_descripcion_alter_products_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
