# Generated by Django 4.1.5 on 2023-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='precio',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imagen',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='products_images'),
        ),
    ]
