# Generated by Django 4.1.5 on 2023-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_categoria_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('makeups', 'makeups'), ('accessories', 'accessories')], max_length=15),
        ),
    ]
