# Generated by Django 4.1.5 on 2023-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('face', 'face'), ('body', 'body')], max_length=15)),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='products_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
